---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: empms-employee
  name: empms-employee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: empms-employee
  template:
    metadata:
      labels:
        app: empms-employee
    spec:
      containers:
      - image: kaifshakeel/empms-employee:1.0
        name: empms-employee
        ports:
        - containerPort: 8083
---
kind: Service
apiVersion: v1
metadata:
  name: empms-employee
spec:
  type: ClusterIP
  selector:
    app: empms-employee
  ports:
  - protocol: TCP
    port: 8083
